# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wut < Formula
  desc "Route accidental natural-language shell input to your AI harness"
  homepage "https://github.com/sonyabytes/wut"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.1/wut_Darwin_x86_64.tar.gz"
      sha256 "a1ae2a7cf9fefef99f1d059f0cfcb3276d60e811ac0498d80601487949aa0542"

      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.1/wut_Darwin_arm64.tar.gz"
      sha256 "98aa8c8f5dc0a6e16b367cfc2f0520c40953053bb9e14effc71684041441d70c"

      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.1/wut_Linux_x86_64.tar.gz"
      sha256 "72aef85a4effc7ebbca08d432afab9715a91b288463ff236c8a63e9556cd46c3"
      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.1/wut_Linux_arm64.tar.gz"
      sha256 "f54692b5b7f908542269be8b093d9ac0c02269ba3c8a902ca225008a90d336ab"
      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  test do
    system "#{bin}/wut", "version"
  end
end
