# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wut < Formula
  desc "Route accidental natural-language shell input to your AI harness"
  homepage "https://github.com/sonyaihub/wut"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyaihub/wut/releases/download/v0.1.0/wut_Darwin_x86_64.tar.gz"
      sha256 "4bac6daea583c3798e1c9e2d8af5678c459872d475a1f43fcbe056d04cf6c5ed"

      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyaihub/wut/releases/download/v0.1.0/wut_Darwin_arm64.tar.gz"
      sha256 "2b5d1ef3d156a11f8e898a452462a2bbc53497c653b24af6b7772a44cfed2f01"

      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyaihub/wut/releases/download/v0.1.0/wut_Linux_x86_64.tar.gz"
      sha256 "d367b798edb6002ff030ea38b321424f4b7ed220378c20ebe3b75b36ef2b4496"
      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyaihub/wut/releases/download/v0.1.0/wut_Linux_arm64.tar.gz"
      sha256 "4b08d26c89dede11620a33474df12ce60d3dafe09c405ae44b544a2491e3c3d9"
      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  test do
    system "#{bin}/wut", "version"
  end
end
